"use client";
import { Header } from "@/components/Header.component";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "use-shopping-cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const stripeKey = process.env.YOUR_STRIPE_PUBLIC_KEY as string;

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider cartMode="checkout-session" stripe={stripeKey} currency="USD" shouldPersist={true}>
          <Header />
          {children}
        </CartProvider>
        ,
      </body>
    </html>
  );
}
